### ISSUE TITLE
Useful dotfiles

### ISSUE THREAD

**Issue by AdamMomen** [hobord/dotfiles-osx#1]
Hey @hobord 

Thanks for sharing your dotfiles they are quite handful I found your profile from one of the primegen repos, I just want to thank about for making this public. I find this very valuable especially that I am new OSX user coming from linux background.

What tool do you use for managing dotfiles and what are your thoughts about stow?

**Comment by hobord** [comment]
https://www.ackama.com/what-we-think/the-best-way-to-store-your-dotfiles-a-bare-git-repository-explained/
